### ISSUE TITLE
new retry and disqualification keyvalue configs

### ISSUE THREAD

**Issue by luttje** [luttje/gmod-minigolf#3]
first feedback ;) (ideas) :
- In `minigolf_hole_start` add a new input : `infinite_retry (int)` (in order to be able to replay endlessly even after a disqualification or after finished the hole)

`infinite_retry` values : 
`nil or x = 0 or x > 2` : no retry on disqualification or finished
`x = 1` : no retry on disqualification and retry on finished
`x = 2` : retry in disqualification or finished

`for old maps` : default `nil` because their maps has not their input

- In `minigolf_hole_start` add a new input : `infinite_retry_disqualification_max (int)` (number of max retry when disqualification)

`infinite_retry_disqualification_max` values :
`x <= -1` : infinite
`x > 0` : x retry

`for old maps` : default `0` because their maps has not their input

- In `minigolf_hole_start` add a new input : `infinite_retry_finished_max (int)` (number of max retry when finished hole)

`infinite_retry_finished_max` values :
`x <= -1` : infinite
`x > 0` : x retry

`for old maps` : default `0` because their maps has not their input

_Originally posted by @rayzox57 in https://github.com/luttje/gmod-minigolf/issues/1#issuecomment-1186198054_

**Comment by rayzox57** [comment]
More precision about this :

    `infinite_retry_global` =
	[
           -1: "No, i want settings any events !",
		0: "No (override all others Infite Retry choose !)"
		1: "Yes (override all others Infite Retry choose !)"
	]

    `infinite_retry_time` =
	[
		0: "No"
		1: "Yes"
	]

    `infinite_retry_strokes` =
	[
		0: "No"
		1: "Yes"
	]

    `infinite_retry_success` =
	[
		0: "No"
		1: "Yes"
	]


And in code for any parameters in this list :

x = x or 0 // if x is nil then 0 or x [ x = a parameter]

**Comment by rayzox57** [comment]
`infinite_retry_time_number`(integer): "Max Retry (Time Limit)" : 0 : "When player play golf and fail with time limit, he can retry X times (-1 : infinite)"
    `infinite_retry_strokes_number`(integer): "Max Retry (Max Strokes)" : 0 : "When player play golf and fail with max strokes, he can retry X times (-1 : infinite)"
    `infinite_retry_success_number`(integer): "Max Retry (On Success Hole)" : 0 : "When player play golf and pass the hole, he can retry X times (-1 : infinite)"

And in code for any parameters in this list :
x = x or 0 // if x is nil then 0 or x [ x = a parameter]

**Comment by rayzox57** [comment]
Oh ! Nevermind ! I see you can retry when you have max strokes (when the hole dont have course ^^')

Edit 23:13 : oh, its when you have more 2 hole you can't retry, i think you need to change this : if the golf hole has no course, you can free use them (infinite retry etc ...)

**Comment by rayzox57** [comment]
**The fgd file for Hammer :**
[minigolf.txt](https://github.com/luttje/gmod-minigolf/files/9126598/minigolf.txt)

_**Installation Steps :**_
`Just change "txt" format to "fgd", move it to GarrysMod/bin folder, and you can import this in Hammer (Tools > Options > Game Configurations > Game Data Files > Add)`

**Comment by luttje** [comment]
I've added the configurations you suggested. It differs slightly from how you suggested it, but all the same things should be possible.

### New `minigolf_hole_start` properties

  * `maxRetriesAfterCompleting`: how many times a player can retry this hole after completing it. -1 for infinite, 0 for no retries until all holes have been finished

  * `maxRetriesAfterTimeLimit`: how many times a player can retry this hole after reaching the time limit. -1 for infinite, 0 for no retries until all holes have been finished

  * `maxRetriesAfterMaxStrokes`: how many times a player can retry this hole after reaching the maximum amount of strokes. -1 for infinite, 0 for no retries until all holes have been finished


### New `minigolf_config` entity
A point entity that dictates how the addon should behave. It can set default information for all holes. There should be only one of this entity on a map.

#### Available Properties:
  * `defaultMaxRetriesAfterCompleting`: How many times a player can retry any hole after completing it. The maxRetriesAfterCompleting property on a hole overrides this. -1 for infinite, 0 for no retries until all holes have been finished (default: 0)

  * `defaultMaxRetriesAfterTimeLimit`: How many times a player can retry any hole after reaching the time limit. The maxRetriesAfterTimeLimit property on a hole overrides this. -1 for infinite, 0 for no retries until all holes have been finished (default: 0)

  * `defaultMaxRetriesAfterMaxStrokes`: How many times a player can retry any hole after reaching the maximum amount of strokes. The maxRetriesAfterMaxStrokes property on a hole overrides this. -1 for infinite, 0 for no retries until all holes have been finished (default: 0)

**Comment by luttje** [comment]
PS: This is not yet in the steam workshop version. I will update that after I also implement your other suggestion.

**Comment by luttje** [comment]
I've updated the workshop addon.

I hope you enjoy these changes!
