### ISSUE TITLE
Add Hold/Release Power Up/Down ("key to define" to switch [Scroll <> Hold/Release])

### ISSUE THREAD

**Issue by rayzox57** [luttje/gmod-minigolf#4]
**Is your feature request related to an issue? Please describe.**
Nope

**Describe the solution you want**
Added the ability to switch to auto power mode, pressing a "key to set" to change power mode. By holding down the left mouse key, the power goes up and down. When we release the power is sent.

**Describe the alternatives you have considered**
Press a key to switch mode: scroll to change the power, press and release the mouse key

**Additional Context**
Can make the experience more enjoyable, as many games have this system in place

**Comment by luttje** [comment]
I will add this again. One of the earliest versions I made of Minigolf had that, but my friends didn't like it so I changed it to what it is now.

Adding this as an option is a great compromise. I'll also add a console variable so server admins can enforce a certain type of power mode

**Comment by rayzox57** [comment]
Perfect :+1: ! Thank !
